{{- range .Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  {{- if .path }}
data:
  {{ .name }}: |-
{{ $.Files.Get .file | indent 4}}
  {{- else }}
data: {{ .data | toYaml | nindent 2 }}
  {{- end }}
...
{{- end }}