
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
	meta.helm.sh/release-namespace: {{ $.Values.namespace }}
	meta.helm.sh/release-name: {{ $.Chart.Name }}
  labels:
	app: {{ $.Values.appname }}
	app.kubernetes.io/component: {{ $.Values.appname }}
	app.kubernetes.io/instance: {{ $.Values.appname }}
	app.kubernetes.io/name: {{ $.Values.appname }}
	app.kubernetes.io/part-of: {{ $.Values.appname }}
	app.kubernetes.io/managed-by: Helm
  name: {{ $.Values.appname }}
  namespace: {{ $.Values.namespace }}
spec:
  {{- if $.Values.ingress.tls }}
  tls:
	- hosts: {{ $.Values.ingress.hostnames | toYaml | nindent 6 }}
	  secretName: {{ $.Values.ingress.tlsSecret }}
  {{- end }}
  rules:
	- host: {{ $.Values.hostname }}
	  http:
		paths:
		  {{- range $.Values.microservices }}
		  {{- if and (ne .ingress.path "/") (ne .ingress.path "none") }}
		  - path: {{ .ingress.path }}
			pathType: Prefix
			backend:
			  service:
				name: {{ .name }}
				port:
				  number: {{ .service.port }}
		  {{- end }}
		  {{- end }}
		  {{- range $.Values.extendedPaths }}
		  {{- if and (ne .path "/") (ne .path "none") }}
		  - path: {{ .path }}
			pathType: Prefix
			backend:
			  service:
				name: {{ .service.name }}
				port:
				  number: {{ .service.port }}
		  {{- end }}
		  {{- end }}
		  {{- range $.Values.microservices }}
		  {{- if eq .ingress.path "/*" }}
		  - path: {{ .ingress.path }}
			pathType: Prefix
			backend:
			  service:
				name: {{ .service.name }}
				port:
				  number: {{ .service.port }}
		  {{- end }}
		  {{- end }}