{{- range .Values.secrets }}
---
apiversion: v1
kind: Secret
metadata:
    name: {{ .name }}
    namespace: {{  $.Values.nanespace }}
data: {{ .data | toYaml | nindent 2 }}
type: {{ .type }}
...
{{- end }}